version: '3.8'
services:
  music_gen:
    build:
      context: .
    container_name: music_gen
    volumes:
      - ./huggingface:/root/.cache/huggingface
      - ./output:/app/output
      - ./prompts.txt:/app/prompts.txt
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - DURATION=300
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]